
import { UserRole } from '@/types/user';

export interface Message {
  id: string;
  content: string;
  sender: 'user' | 'ai';
  timestamp: Date;
  aiAssistant?: string;
  status?: 'sending' | 'sent' | 'processing';
}

// Mock user data - in real implementation this would come from the portal login
export const mockUser = {
  name: 'John Smith',
  department: 'CAN program',
  role: 'Public Adjuster',
  accessLevel: 'Senior',
  homeState: 'Florida',
  userType: {
    type: 'developer' as const,
    permissions: {
      manageUsers: false,
      manageAIs: true,
      editAIPrompts: true,
      systemSettings: false
    }
  } as UserRole
};

export const initialMessages: Message[] = [];

export const validateFile = (file: File): string | null => {
  if (file.type !== 'application/pdf') {
    return 'Please upload a PDF file only.';
  }
  if (file.size > 10 * 1024 * 1024) { // 10MB limit
    return 'File size must be less than 10MB.';
  }
  return null;
};

export const assignTraining = async (courseName: string) => {
  // TODO: Implement real training assignment API call
  console.log(`Training assignment API call needed for: ${courseName}`);
  // throw new Error('Training assignment API not yet implemented');
};

export const downloadPolicyReport = (user: { name: string; role: string; department: string }) => {
  const reportContent = `POLICY REVIEW REPORT
Generated by: Coastal Claims Services Policy Pro™
Generated on: ${new Date().toLocaleDateString()}
Reviewed by: ${user.name} (${user.role})

📘 POLICY BASICS

Named Insured(s): FRANK J HAWKINS
Insured Address: 2917 CAPTIVA WAY, SARASOTA, FL 34231

✅ Mortgage
Name: Not Specified
Loan #: Not Specified
Mailing Address: Not Specified

✅ Insurance Carrier
Carrier: Farmers Casualty Insurance Company
Policy Period: 10/14/2023 to 10/14/2024
Agent (information and address): Not Specified

🏠 PROPERTY DETAILS (UNDERWRITING SNAPSHOT)

County property appraiser search website: https://www.sc-pa.com/
Year Built: 1974
Square Footage: Not Specified
Roof Year: Not Specified
Foundation: Frame Construction
Interior/Exterior: Not Specified

🧾 DEDUCTIBLES SECTION

Type                    Amount
Hurricane              $10,018 (2% of Coverage A)
All Other Perils       $1,000

🛡️ COVERAGE TOTALS SECTION

Coverage    Description                    Limit
A          Dwelling                       $500,900
B          Other Structures               $100,180
C          Personal Property              $375,675
D          Loss of Use (up to 24 mo.)     $264,665
A,B,C,D    Total Combined                 $1,241,420

📄 ENDORSEMENTS

Limited Replacement Plus Incl
Replacement Cost on Contents Incl
13 - Back Up of Sewer, Drain and Sump Pump Coverage: $250 Deductible
15 - Ordinance or Law 50% of Coverage A
25 - Personal Injury Coverage
Forms and Endorsements: 7083-000 (0698), H633F, H768, H698G, H302B, H326, H101, H445FL, H781, H870, H331C, H708C, H603

⚠️ EXCLUSIONS / GAPS / LIMITATIONS

Matching endorsement: No
Cosmetic Endorsement: No
Roof payment schedule: No
Right to repair / Our option: Clarification Needed – language unclear
ACV (actual cash value endorsement): No
Ensuing loss: (storm/wind created an opening)
Language not found regarding "Sand" or associated ensuing loss coverage.

📝 EXAMINATION UNDER OATH (EUO)

Party                    EUO Requirement
Insured                 ✅ Yes
Public Adjuster (PA)    ❌ No

Note: PAs cannot be compelled to EUO, but may be subpoenaed for records or deposition in litigation.

⏳ LEGAL / STATUTORY INFO

Statute of Limitations to File Claim: Not Specified
"Suit Against Us" Clause Language: Not Specified

Appraisal
Appraisal Clause Present? Yes — Language not provided in excerpts, assumed present based on standard Florida HO policies.

🗓️ REVIEW DATA

Generated on: ${new Date().toLocaleDateString()}
Reviewed by: Coastal Claims Services Policy Pro™

---
This report was generated by Coastal AI Policy Expert for ${user.name}
Department: ${user.department}
Role: ${user.role}`;

  const blob = new Blob([reportContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'Frank_Hawkins_Policy_Review_Report.txt';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
